#!/bin/bash
set -e

cd "$(dirname "$0")"

# Initial setup
if [[ "$1" == "install" ]]; then
    sudo xargs -a ../packages.txt apt install -y
    sudo mkdir -p /etc/rpiNode
    sudo mkdir -p /srv/rpiNode
    sudo mkdir -p /srv/rpiNode/html
    sudo cp -v ../html/*.* /srv/rpiNode/html/
fi

# -- tmp for development use --
if [[ "$1" == "update" ]]; then
    sudo cp -v ../html/*.* /srv/rpiNode/html/
fi

# Check for "debug" argument
CFLAGS="-Wall"
LDFLAGS="-Wall -pthread -lsqlite3 -lmicrohttpd -ljansson $(pkg-config --cflags --libs avahi-client) -lm"

if [[ "$1" == "debug" ]]; then
    echo "Debug mode enabled"
    CFLAGS="$CFLAGS -g"
    LDFLAGS="-g $LDFLAGS"
fi

# Map source files to desired object files
declare -A FILE_MAP=(
    [main.c]=main.o
    [utils/sleepMs.c]=sleepMs.o
    [utils/readFile.c]=readFile.o
    [utils/setTmpfs.c]=setTmpfs.o
    [local/db/initDB.c]=initDB.o
    [utils/strReplace.c]=strReplace.o
    [utils/updateTags.c]=updateTags.o
    [local/db/saveTags.c]=saveTags.o
    [local/db/writeToDB.c]=writeToDB.o
    [utils/getTimeStamp.c]=getTimeStamp.o
    [utils/signalHandler.c]=signalHandler.o
    [utils/getLineFromCmd.c]=getLineFromCmd.o
    [utils/getLocalIPList.c]=getLocalIPList.o
    [config/readConfigFile.c]=readConfigFile.o
    [network/http/serveHttp.c]=serveHttp.o
    [network/mDNS/mDnsService.c]=mDnsService.o
    [sensors/DS18B20/readSlave.c]=readSlave.o
    [network/http/routeRequest.c]=routeRequest.o
    [sensors/MPU6050/readMPU6050.c]=readMPU6050.o
    [sensors/DS18B20/readDS18B20.c]=readDS18B20.o
    [sensors/MPU6050/assignValues.c]=assignValues.o
    [network/http/answerConnection.c]=answerConnection.o
    [network/http/queueErrorResponse.c]=queueErrorResponse.o
    [sensors/MPU6050/calculateAngles.c]=calculateAngles.o
    [sensors/DS18B20/scanForW1Devices.c]=scanForW1Devices.o
    [network/http/handlers/handleFile.c]=handleFile.o
    [network/http/handlers/handleStatus.c]=handleStatus.o
    [sensors/MPU6050/smoothingMovingAverage.c]=smoothingMovingAverage.o
)

OBJ_FILES=()

echo "Compiling source files..."

for src in "${!FILE_MAP[@]}"; do
    obj="${FILE_MAP[$src]}"
    gcc -c $CFLAGS "$src" -o "$obj" $(pkg-config --cflags avahi-client)
    OBJ_FILES+=("$obj")
done

echo "Linking..."
gcc "${OBJ_FILES[@]}" -o ../rpiNode $LDFLAGS

echo "Cleaning up..."
rm -f *.o
find . -type f \( -name "*.c" -o -name "*.h" -o -name "*.txt" \) -exec chmod -x {} +

echo "Build complete!"
